channels:
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2019.4
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.1.5
  - kiwisolver=1.2.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - readline=8.0
  - requests=2.24.0
  - scipy=1.5.0
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11

